import type { Metadata } from "next";
import { Scope_One } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const scopeOne = Scope_One({ subsets: ["latin"], display: 'swap', weight: '400' });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(scopeOne.className, 'h-screen overflow-hidden')}>{children}</body>
    </html>
  );
}
